# Provision Azure infrastructure for FindIt
# Usage: .\deploy_infra.ps1
# This creates the resource group and all Azure resources using the Bicep template.
# Run this ONCE before the first deploy. Re-running is safe (idempotent).

$ResourceGroup = "rg-memory-assistant"
$Location      = "eastus"
$BicepFile     = "$PSScriptRoot\..\infra\main.bicep"

Write-Host ""
Write-Host "=== FindIt - Infrastructure Provisioning ===" -ForegroundColor Cyan
Write-Host ""

# Check Azure CLI login
$azAccount = az account show --query "user.name" -o tsv 2>$null
if (-not $azAccount) {
    Write-Host "Not logged in. Run 'az login' first." -ForegroundColor Red
    exit 1
}
Write-Host "Logged in as: $azAccount" -ForegroundColor Green

# Check Bicep file exists
if (-not (Test-Path $BicepFile)) {
    Write-Host "Bicep file not found: $BicepFile" -ForegroundColor Red
    exit 1
}

# Create resource group
Write-Host ""
Write-Host "Creating resource group: $ResourceGroup ($Location)..." -ForegroundColor Yellow
az group create --name $ResourceGroup --location $Location -o none
if ($LASTEXITCODE -ne 0) { Write-Host "Failed to create resource group." -ForegroundColor Red; exit 1 }
Write-Host "Resource group ready." -ForegroundColor Green

# Deploy Bicep template
Write-Host ""
Write-Host "Deploying infrastructure (this takes 3-5 minutes)..." -ForegroundColor Yellow
$deployment = az deployment group create `
    --resource-group $ResourceGroup `
    --template-file $BicepFile `
    --query "properties.outputs" `
    -o json 2>$null

if ($LASTEXITCODE -ne 0) {
    Write-Host "Bicep deployment failed:" -ForegroundColor Red
    Write-Host $deployment
    exit 1
}

# Parse outputs
$outputs = $deployment | ConvertFrom-Json
$acrName            = $outputs.acrName.value
$acrLoginServer     = $outputs.acrLoginServer.value
$storageAccountName = $outputs.storageAccountName.value
$storageAccountUrl  = $outputs.storageAccountUrl.value
$backendUrl         = $outputs.backendUrl.value
$frontendUrl        = $outputs.frontendUrl.value
$backendAppName     = $outputs.backendAppName.value
$frontendAppName    = $outputs.frontendAppName.value

# Write generated config file (sourced by deploy_config.ps1)
$configPath = "$PSScriptRoot\deploy_config.generated.ps1"
@"
# Auto-generated by deploy_infra.ps1 — do not edit manually
`$AcrName            = "$acrName"
`$StorageAccountName = "$storageAccountName"
"@ | Set-Content -Path $configPath -Encoding UTF8

# Grant current user Storage Blob Data Contributor on the new storage account (for local dev)
Write-Host ""
Write-Host "Granting storage access to current user (for local development)..." -ForegroundColor Yellow
$userId = az ad signed-in-user show --query id -o tsv 2>$null
$storageId = az storage account show --name $storageAccountName --resource-group $ResourceGroup --query id -o tsv 2>$null
if ($userId -and $storageId) {
    az role assignment create --assignee $userId --role "Storage Blob Data Contributor" --scope $storageId -o none 2>$null
    if ($LASTEXITCODE -eq 0) {
        Write-Host "Storage Blob Data Contributor role assigned to current user." -ForegroundColor Green
    } else {
        Write-Host "Could not assign role (may already exist). Assign manually if needed." -ForegroundColor Yellow
    }
} else {
    Write-Host "Could not determine user/storage ID. Assign RBAC manually for local dev." -ForegroundColor Yellow
}

Write-Host ""
Write-Host "=== Infrastructure Provisioned ===" -ForegroundColor Green
Write-Host ""
Write-Host "  Resource Group  : $ResourceGroup" -ForegroundColor White
Write-Host "  ACR             : $acrLoginServer" -ForegroundColor White
Write-Host "  Storage Account : $storageAccountName" -ForegroundColor White
Write-Host "  Storage URL     : $storageAccountUrl" -ForegroundColor White
Write-Host "  Backend App     : $backendAppName" -ForegroundColor White
Write-Host "  Frontend App    : $frontendAppName" -ForegroundColor White
Write-Host "  Backend URL     : https://$backendUrl" -ForegroundColor White
Write-Host "  Frontend URL    : https://$frontendUrl" -ForegroundColor White
Write-Host ""
Write-Host "Config saved to: $configPath" -ForegroundColor Gray

# Update local server/.env with the new storage URL if it exists
$envFile = "$PSScriptRoot\..\server\.env"
if (Test-Path $envFile) {
    $envContent = Get-Content $envFile -Raw
    if ($envContent -match "AZURE_STORAGE_ACCOUNT_URL=") {
        $envContent = $envContent -replace "AZURE_STORAGE_ACCOUNT_URL=.*", "AZURE_STORAGE_ACCOUNT_URL=$storageAccountUrl"
        $envContent | Set-Content -Path $envFile -NoNewline
        Write-Host "Updated server\.env with new storage URL." -ForegroundColor Green
    }
}
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Cyan
Write-Host "  1. Set your Gemini API key:  .\deploy.ps1  (or set it manually)" -ForegroundColor White
Write-Host "  2. Deploy the app:           .\deploy.ps1" -ForegroundColor White
